version: '3.1'
services:
  dashboard:
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:3000
    command: ["node", "web-server.js"]
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  bot:
    build:
      context: .
      dockerfile: Dockerfile.backend