# Use the official Node image as a parent image.
FROM node:18.16-alpine

# Copy all files from the frontend directory into the image.
COPY frontend /app

# Change the working directory to the app directory.
WORKDIR /app

# Install the dependencies from the package.json file.
RUN npm install

# Build the app.
RUN npm run build

# Set the command to run the app when the container starts.
CMD ["node", "web-server.js"]
