# Use the official Node image as a parent image.
FROM node:18.16-alpine

# Copy all files from the backend directory into the image.
COPY backend /app

# Change the working directory to the app directory.
WORKDIR /app

# Install the dependencies from the package.json file.
RUN npm install

# Build the app.
RUN npx tsc -p .

# Set the command to run the app when the container starts.
CMD ["node", "src/index.js"]