version: '3.1'
services:
  dashboard:
    container_name: frogbot-dashboard
    restart: always
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:3000
    command: ["node", "web-server.js"]
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  backend:
    container_name: frogbot-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend